doc: adapt README to crates.io
collabora/bmap-rs pull request #60
Opened 2022-12-19 14:01 UTC by Razaloc

At this moment bmap-rs and bmap-parser share the same README. This is problematic because in crates.io, once published, bmap-parser contains references to bmap-rs while if should be independent from it.

Fix the original README file.
Add a new README file for bmap-parser.

Signed-off-by: Rafael Garcia Ruiz <rafael.garcia@collabora.com>

2022-12-19 14:28 UTC, Razaloc commented
Just in case we want to quick fix the README problem, I've committed a bump to versions.

2022-12-19 14:31 UTC, obbardc requested changes

2022-12-19 14:31 UTC, obbardc commented on bmap-parser/README.md
> +The bmap-parser crate aims to implement tools related to bmap. The inspiration for it
bmap-parser doesn't implement tools, it implements the parsing bits for bmap files :-)

2023-02-18 10:41 UTC, obbardc commented
can you drop the bors commit and the version bump commit ?
We are gonna drop bors at some point, and I think we should handle the release separately.

2026-04-23 07:47 UTC, sjoerdsimons commented
outdated, stale, closing

2026-04-23 07:47 UTC, closed without merging